# Generated by Django 6.0.3 on 2026-03-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=256)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='branch_app.branch')),
            ],
        ),
    ]
